query {
  user (login: "Hacksore"){
    contributionsCollection {
      contributionCalendar {
        totalContributions,
        weeks {
          contributionDays {
            contributionCount
          }
        }
      }
    }
  }
}
